version: "3.9"
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      timeout: 20s
      retries: 10
  mongo:
    image: mongo
    ports:
      - "8081:8081"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 20
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  service-gateway:
    build: service-gateway
    ports:
      - "8080:80"
  service-authorization:
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: service-authorization
  service-candidate:
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: service-candidate
  service-party:
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: service-party
  service-user:
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: service-user
  service-voting-form:
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: service-voting-form

networks:
  default:
    external:
      name: voting