version: "3.9"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      timeout: 20s
      retries: 10
  mongo:
    image: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 20
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  service-gateway:
    build: service-gateway
    container_name: service-gateway
    ports:
      - "8080:80"
  service-authorization:
    container_name: service-authorization
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: service-authorization
  service-candidate:
    container_name: service-candidate
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: service-candidate
  service-party:
    container_name: service-party
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: service-party
  service-user:
    container_name: service-user
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: service-user
  service-voting-form:
    container_name: service-voting-form
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: service-voting-form

networks:
  default:
    external:
      name: voting
