server:
  port: 80
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql:3306/onlinevotingplatform_form?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
services:
  service-candidate:
    hostname: service-candidate
    port: 80