server:
  port: 80
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq
    password: guest
    port: 5672
    username: guest
  data:
    mongodb:
      host: mongo