name: Push service-authorization to Docker Hub
env:
  service: service-authorization
on:
  push:
   paths: service-authorization/**
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        working-directory: ${{ env.service }}
        run: mvn clean package -P prod
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ env.service }}
          push: true
          tags: robinvandenhurk/vote-${{ env.service }}:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
