name: service-user
defaults:
  run:
    working-directory: ${{ GITHUB_WORKFLOW }}
on:
  push:
    paths: service-user/**
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: robinvandenhurk/vote-${{ env.service }}
          tags: latest
